# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Toprogrammer
email: laixintao1995@163.com
description: > # this means to ignore newlines until "baseurl:"
    Dreistigkeit siegt.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http:/programmer.top" # the base hostname & protocol for your site
twitter_username: laixintao
github_username:  laixintao

# Build settings
markdown: kramdown
